name: Haskell CI
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install stack
        run: curl -sSL https://get.haskellstack.org/ | sh

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Build
        run: stack build

      - name: Package generator
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/hdc
          cp "$dir/hdc" /package/hdc
          cp -r README.md package/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: haskell-docs-cli-${{ runner.os }}
          path: package
